#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: makefile (file name) ..."
else

    for file in "$@"
    do
        if test -f "$file.html"; then
            echo "$file exists."
        else
            cat > $file.html <<STOP
<!DOCTYPE hmtl>
<html>
    <head>
        <title>$file</title>
    </head>
    <body>
    </body>
</html>
STOP

        fi


    done

fi
